# Generated by Django 5.2 on 2025-05-21 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('analyze', '分析'), ('export', '导出'), ('import', '导入')], max_length=20, verbose_name='操作类型')),
                ('description', models.CharField(max_length=200, verbose_name='操作描述')),
                ('data', models.JSONField(verbose_name='操作数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(verbose_name='用户代理')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '历史记录',
                'verbose_name_plural': '历史记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50, verbose_name='字段名')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='旧值')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='新值')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='history.history', verbose_name='历史记录')),
            ],
            options={
                'verbose_name': '历史记录详情',
                'verbose_name_plural': '历史记录详情',
            },
        ),
    ]
