# Generated by Django 5.2 on 2025-05-21 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='拓扑名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('data', models.JSONField(verbose_name='拓扑数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('tags', models.CharField(blank=True, max_length=200, null=True, verbose_name='标签')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topologies', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '拓扑图',
                'verbose_name_plural': '拓扑图',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TopologyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=50, verbose_name='分析类型')),
                ('result', models.JSONField(verbose_name='分析结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.CharField(default='completed', max_length=20, verbose_name='状态')),
                ('topology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='topology.topology', verbose_name='拓扑图')),
            ],
            options={
                'verbose_name': '拓扑分析',
                'verbose_name_plural': '拓扑分析',
                'ordering': ['-created_at'],
            },
        ),
    ]
