# Generated by Django 5.2 on 2025-05-23 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('ip', models.CharField(max_length=100, verbose_name='IP地址')),
                ('mac', models.CharField(max_length=100, verbose_name='MAC地址')),
                ('vendor', models.CharField(max_length=100, verbose_name='厂商')),
                ('os_version', models.CharField(max_length=100, verbose_name='操作系统版本')),
                ('location', models.CharField(max_length=100, verbose_name='位置')),
                ('status', models.CharField(max_length=100, verbose_name='状态')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='最后发现时间')),
            ],
        ),
        migrations.CreateModel(
            name='historySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot_json', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='vlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='VLAN名称')),
                ('number', models.IntegerField(verbose_name='VLAN号')),
            ],
        ),
        migrations.RemoveField(
            model_name='topologyanalysis',
            name='topology',
        ),
        migrations.CreateModel(
            name='interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='接口名称')),
                ('ip', models.CharField(max_length=100, verbose_name='IP地址')),
                ('mac', models.CharField(max_length=100, verbose_name='MAC地址')),
                ('status', models.CharField(max_length=100, verbose_name='状态')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='topology.device', verbose_name='设备')),
            ],
        ),
        migrations.CreateModel(
            name='link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='状态')),
                ('link_type', models.CharField(max_length=100, verbose_name='链路类型')),
                ('interface_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_a', to='topology.interface', verbose_name='接口A')),
                ('interface_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_b', to='topology.interface', verbose_name='接口B')),
            ],
        ),
        migrations.DeleteModel(
            name='Topology',
        ),
        migrations.DeleteModel(
            name='TopologyAnalysis',
        ),
    ]
