# Generated by Django 5.2 on 2025-05-21 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('config_type', models.CharField(choices=[('system', '系统配置'), ('network', '网络配置'), ('security', '安全配置'), ('custom', '自定义配置')], max_length=20, verbose_name='配置类型')),
                ('template_data', models.JSONField(verbose_name='模板数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
            ],
            options={
                'verbose_name': '配置模板',
                'verbose_name_plural': '配置模板',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('config_type', models.CharField(choices=[('system', '系统配置'), ('network', '网络配置'), ('security', '安全配置'), ('custom', '自定义配置')], default='custom', max_length=20, verbose_name='配置类型')),
                ('data', models.JSONField(verbose_name='配置数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('version', models.IntegerField(default=1, verbose_name='版本号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '配置',
                'verbose_name_plural': '配置',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'name', 'version')},
            },
        ),
    ]
