# Generated by Django 5.2 on 2025-05-27 12:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_range', models.CharField(max_length=100)),
                ('asn', models.CharField(blank=True, max_length=20, null=True)),
                ('geo', models.CharField(blank=True, max_length=10, null=True)),
                ('target', models.CharField(help_text='Target IP or IP range (e.g., 192.168.1.0/24)', max_length=255)),
                ('scan_type', models.CharField(choices=[('nmap', 'Nmap Scan'), ('masscan', 'Masscan Scan'), ('snmpwalk', 'SNMP Walk')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('scan_rate', models.CharField(blank=True, help_text='Packets per second for masscan', max_length=20, null=True)),
                ('scan_ports', models.CharField(blank=True, help_text='Port range for masscan (e.g., 1-65535)', max_length=100, null=True)),
                ('scan_interface', models.CharField(blank=True, help_text='Network interface for masscan', max_length=100, null=True)),
                ('scan_wait', models.CharField(blank=True, help_text='Wait time for masscan', max_length=20, null=True)),
                ('snmp_community', models.CharField(blank=True, help_text='SNMP community string', max_length=100, null=True)),
                ('snmp_version', models.CharField(blank=True, help_text='SNMP version (1, 2c, 3)', max_length=10, null=True)),
                ('snmp_mib', models.CharField(blank=True, help_text='SNMP MIB to query', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=10, null=True)),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('os_info', models.CharField(blank=True, max_length=255, null=True)),
                ('snmp_data', models.JSONField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='scanner.scantask')),
            ],
            options={
                'db_table': 'scan_results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip_address'], name='scan_result_ip_addr_a6935b_idx'), models.Index(fields=['task'], name='scan_result_task_id_a0e8a1_idx')],
            },
        ),
    ]
